name: Secrets
on:
  push:
    branches: [main]
jobs:
  secrets:
    runs-on: windows-latest
    steps:
#      - uses: actions/checkout@v2
      - name: RIOT API Key
#        run: |
#            echo "Hello, ${{ secrets.API_KEY }}"
#        with: # Set the secret as an input
#          RIOT_API_KEY: ${{ secrets.API_KEY }}
        env: # Or as an environment variable
          RIOT_API_KEY: ${{ secrets.API_KEY }}
        run: echo $RIOT_API_KEY