on: [ push ]
steps:
  - name: RIOT API Key
    with: # Set the secret as an input
      RIOT_API_KEY: ${{ secrets.API_KEY }}
    env: # Or as an environment variable
      RIOT_API_KEY: ${{ secrets.API_KEY }}