name: Secrets
on:
  push:
    branches: [main]
jobs:
  secrets:
    runs-on: windows-latest
    steps:
#      - uses: actions/checkout@v2
      - run: |
            echo "Hello, ${{ secrets.API_KEY }}"
      - name: RIOT API Key
        with: # Set the secret as an input
          RIOT_API_KEY: ${{ secrets.API_KEY }}
        env: # Or as an environment variable
          RIOT_API_KEY: ${{ secrets.API_KEY }}